version: "3.7"

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: forbiddenCardChecker-api

  website:
    build:
      context: website
      dockerfile: Dockerfile
    container_name: forbiddenCardChecker-website
    ports:
      - 9102:80
    depends_on:
      - api
